language: python
python:
  - "3.5"
install:
  - pip install -r ./server/misc/requirements.txt
services:
  - docker
env:
  - DIVVY_ENV=development_docker
script:
  - python server/manage.py test server

